export const SET_PLAY_LIST = 'SET_PLAY_LIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_CURRENT_PLAY_SONG_INDEX = 'SET_CURRENT_PLAY_SONG_INDEX'

export const SET_CURRENT_PLAY_SONG = 'SET_CURRENT_PLAY_SONG'

export const SET_PLAYING_STATUS = 'SET_PLAYING_STATUS'

export const SET_CATEGORY_GROUP_ID = 'SET_CATEGORY_GROUP_ID'

export const SET_CURRENT_SONG = 'SET_CURRENT_SONG'

export const SET_SEARCH_KEY = 'SET_SEARCH_KEY'

export const SET_SHOW_TOP_BOX = 'SET_SHOW_TOP_BOX'

export const SET_LOGIN_USER = 'SET_LOGIN_USER'

export const SET_USER_TOKEN = 'SET_USER_TOKEN'

export const SET_LOGIN_USER_FAVORITE_DISSTS = 'SET_LOGIN_USER_FAVORITE_DISSTS'

export const SET_LOGIN_USER_FAVORITE_SONG_LIST = 'SET_LOGIN_USER_FAVORITE_SONG_LIST'

export const SET_CURRENT_TOP = 'SET_CURRENT_TOP'

export const SET_ROUTER_STACK_POINTER = 'SET_ROUTER_STACK_POINTER'

export const SET_NEED_LOGIN = 'SET_NEED_LOGIN'

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY'
